#!/usr/bin/env bash
# ==============================================================================
# 🔄 DPI Center — Workspace Environment & Secret Synchronizer
# ==============================================================================
# Pulls authoritative platform secrets from GCP Secret Manager (base-mgmt)
# and deterministically configures local .env and terraform.tfvars.
#
# Eliminates configuration drift across team developer workstations.
# ==============================================================================

set -euo pipefail

COLOR_GREEN="\033[0;32m"
COLOR_YELLOW="\033[1;33m"
COLOR_RED="\033[0;31m"
COLOR_CYAN="\033[0;36m"
COLOR_RESET="\033[0m"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MGMT_PROJECT="base-mgmt"
SECRET_NAME="billing-account-id"

echo "================================================================="
echo -e " 🔄 ${COLOR_CYAN}DPI Center — Workspace Environment Sync${COLOR_RESET}"
echo "================================================================="

# 1. Check gcloud CLI and authentication
if ! command -v gcloud &>/dev/null; then
  echo -e "${COLOR_RED}❌ ERROR: 'gcloud' CLI is not installed.${COLOR_RESET}"
  exit 1
fi

ACTIVE_ACCOUNT=$(gcloud config get-value account 2>/dev/null || true)
if [[ -z "${ACTIVE_ACCOUNT}" || "${ACTIVE_ACCOUNT}" == "(unset)" ]]; then
  echo -e "${COLOR_RED}❌ ERROR: No active gcloud account found.${COLOR_RESET}"
  echo "Please run: gcloud auth login"
  exit 1
fi

echo -e " [OK] Authenticated as: ${COLOR_GREEN}${ACTIVE_ACCOUNT}${COLOR_RESET}"

# 2. Fetch authoritative billing account ID from Secret Manager
echo " ==> Fetching authoritative secrets from GCP Secret Manager (${MGMT_PROJECT})..."
if ! BILLING_ACCOUNT_ID=$(gcloud secrets versions access latest --secret="${SECRET_NAME}" --project="${MGMT_PROJECT}" 2>/dev/null); then
  echo -e "${COLOR_RED}❌ ERROR: Unable to access secret '${SECRET_NAME}' in project '${MGMT_PROJECT}'.${COLOR_RESET}"
  echo "Ensure your Google account (${ACTIVE_ACCOUNT}) has 'Secret Manager Secret Accessor' or 'Editor' on project '${MGMT_PROJECT}'."
  exit 1
fi

# Masked output for log privacy
MASKED_BILLING="${BILLING_ACCOUNT_ID:0:6}-XXXXXX-${BILLING_ACCOUNT_ID: -5}"
echo -e " [OK] Retrieved Billing Account ID: ${COLOR_GREEN}${MASKED_BILLING}${COLOR_RESET}"

# 3. Synchronize root .env file
ENV_FILE="${REPO_ROOT}/.env"
ENV_EXAMPLE="${REPO_ROOT}/.env.example"

if [[ ! -f "${ENV_FILE}" ]]; then
  if [[ -f "${ENV_EXAMPLE}" ]]; then
    cp "${ENV_EXAMPLE}" "${ENV_FILE}"
    echo " [OK] Created .env from template .env.example"
  else
    touch "${ENV_FILE}"
    echo " [OK] Created new .env file"
  fi
fi

# Update or append environment variables in .env
upsert_env_var() {
  local key="$1"
  local val="$2"
  if grep -q "^${key}=" "${ENV_FILE}" 2>/dev/null; then
    sed -i '' "s|^${key}=.*|${key}=\"${val}\"|" "${ENV_FILE}"
  elif grep -q "^# *${key}=" "${ENV_FILE}" 2>/dev/null; then
    sed -i '' "s|^# *${key}=.*|${key}=\"${val}\"|" "${ENV_FILE}"
  else
    echo "${key}=\"${val}\"" >> "${ENV_FILE}"
  fi
}

upsert_env_var "DOMAIN_NAME" "base"
upsert_env_var "BILLING_ACCOUNT_ID" "${BILLING_ACCOUNT_ID}"
upsert_env_var "ORGANIZATION_ID" "350922776586"
upsert_env_var "PARENT_DOMAIN" "dpi.ait.ac.th"
upsert_env_var "REGION" "asia-southeast1"
upsert_env_var "FOLDER_ADMINS" "akraradet@ait.asia,nuttasit@ait.asia"

echo -e " [OK] Synchronized: ${COLOR_GREEN}${ENV_FILE}${COLOR_RESET}"

# 4. Synchronize base-mgmt/terraform/terraform.tfvars
TFVARS_FILE="${REPO_ROOT}/base-mgmt/terraform/terraform.tfvars"
mkdir -p "$(dirname "${TFVARS_FILE}")"

cat << INNER_EOF > "${TFVARS_FILE}"
# ==============================================================================
# Auto-generated by scripts/pull_env.sh from GCP Secret Manager (base-mgmt)
# Generated at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# ==============================================================================

project_id         = "base-mgmt"
region             = "asia-southeast1"
domain_name        = "base.dpi.ait.ac.th."
folder_id          = "740224775327"
billing_account_id = "${BILLING_ACCOUNT_ID}"

# Team Collaborators (Folder IAM)
folder_admins = [
  "akraradet@ait.asia",
  "nuttasit@ait.asia",
]

folder_members = []
INNER_EOF

echo -e " [OK] Synchronized: ${COLOR_GREEN}${TFVARS_FILE}${COLOR_RESET}"

# 5. Set Application Default Credentials quota project if needed
gcloud auth application-default set-quota-project "${MGMT_PROJECT}" 2>/dev/null || true

echo "================================================================="
echo -e " ✅ ${COLOR_GREEN}Workspace synchronization complete! Zero drift verified.${COLOR_RESET}"
echo " You can now run: ./scripts/check_env.sh"
echo "================================================================="
